"""Add role to users

Revision ID: ebd72fff2f2f
Revises: 874d97cd9d1a
Create Date: 2026-09-09 19:56:57.272562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ebd72fff2f2f'
down_revision: Union[str, Sequence[str], None] = '874d97cd9d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('ADMIN', 'HR', 'EMPLOYEE', name='role')
    role_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'HR', 'EMPLOYEE', name='role'), nullable=False, server_default='EMPLOYEE'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    role_enum = postgresql.ENUM('ADMIN', 'HR', 'EMPLOYEE', name='role')
    role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
